# Generated by Django 3.2.4 on 2023-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_user_npahk9', upload_to='images/'),
        ),
    ]
