# Generated by Django 3.2.4 on 2023-05-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='updated_at',
        ),
    ]
