# Generated by Django 3.2.4 on 2023-05-24 20:20

from django.db import migrations, models
import featured.models


class Migration(migrations.Migration):

    dependencies = [
        ('featured', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='featured_date',
            field=models.DateField(default=featured.models.generate_random_date),
        ),
    ]
