# Generated by Django 3.2.4 on 2023-05-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='content',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
    ]
